# .streamlit/secrets.toml

[snowflake]
user = "JUSTIN"
password = "Justin"
account = "i4rsdf.east-us-2.azure"
warehouse = "Compute_wh"
database = "TRIAL"
schema = "PUBLIC"


[snowflake1]
user = "Peter"
password = "Peter#"
account = "das4sdf.us-east-1"
warehouse = "Compute_wh"


[snowflake2]
user = "JUSTIN"
password = "Justin"
account = "ir234f.east-us-2.azure"
warehouse = "Compute_wh"
database = "TRIAL"
schema = "PUBLIC"


[snowflake3]
user = "JUSTIN"
password = "Justin"
account = "irad364.east-us-2.azure"
warehouse = "Compute_wh"
database = "TRIAL"
schema = "PUBLIC"


[snowflake4]
user = "denny"
password = "Mosses"
account = "vodfdf3.east-us-2.azure"
warehouse = "Compute_wh"
database = "TRIAL"
schema = "PUBLIC"

